Vagrant.configure("2") do |config|
    config.vm.define 'lxc-docker-build' do |node_config|
        node_config.vm.box = 'arch64'
        node_config.vm.hostname = 'lxc-docker-build'
        node_config.vm.provider "virtualbox" do |vb|
            memory = 8192
            vb.gui = true
            vb.name = 'lxc-docker-build'
            vb.customize [ 'modifyvm', :id,
                '--name', 'lxc-docker-build',
                '--memory', memory.to_s,
                '--usb', 'off',
                '--usbehci', 'off',
                '--accelerate3d', 'off'
            ]
        end
        node_config.vm.provision "shell", path: "build.sh"
    end
end
